# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMachineLearning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMachineLearning
pod 'Firebase/MLVision', '6.25.0'
# If using an on-device API:
pod 'Firebase/MLVisionTextModel', '6.25.0'
end
